package wordlist

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

type WordlistName string

const (
	NameCommonPasswords   WordlistName = "common-passwords"
	NameCommonUsernames   WordlistName = "common-usernames"
	NameDirectoryWordlist WordlistName = "directory-wordlist"
	NameSubdomainWordlist WordlistName = "subdomain-wordlist"
	NameParameterWordlist WordlistName = "parameter-wordlist"
	NameBackupExtensions  WordlistName = "backup-extensions"
	NameSensitiveFiles    WordlistName = "sensitive-files"
	NameDefaultCreds      WordlistName = "default-creds"
	NameAPIEndpoints      WordlistName = "api-endpoints"
	NameGraphQLWords      WordlistName = "graphql-words"
	NameCloudEndpoints    WordlistName = "cloud-endpoints"
	NameWordPressPaths    WordlistName = "wordpress-paths"
	NamePHPWebshells      WordlistName = "php-webshells"
	NameGitPaths          WordlistName = "git-paths"
	NameEnvFiles          WordlistName = "env-files"
	NameBackupFiles       WordlistName = "backup-files"
	NameHiddenFiles       WordlistName = "hidden-files"
	NameAdminPaths        WordlistName = "admin-paths"
	NameUserEnumPaths     WordlistName = "user-enum-paths"
)

var CommonPasswordsList = []string{
	"123456", "password", "12345678", "qwerty", "123456789",
	"12345", "1234", "111111", "1234567", "dragon",
	"123123", "baseball", "abc123", "football", "monkey",
	"letmein", "shadow", "master", "666666", "qwertyuiop",
	"123321", "mustang", "michael", "654321", "superman",
	"1qaz2wsx", "7777777", "121212", "000000", "qazwsx",
	"123qwe", "killer", "trustno1", "jordan", "jennifer",
	"zxcvbnm", "asdfgh", "hunter", "buster", "soccer",
	"harley", "batman", "andrew", "tigger", "sunshine",
	"iloveyou", "2000", "charlie", "robert", "thomas",
	"hockey", "ranger", "daniel", "starwars", "klaster",
	"112233", "george", "computer", "michelle", "jessica",
	"pepper", "1111", "zxcvbn", "555555", "11111111",
	"131313", "freedom", "777777", "pass", "maggie",
	"159753", "aaaaaa", "ginger", "princess", "joshua",
	"cheese", "amanda", "summer", "love", "ashley",
	"nicole", "chelsea", "biteme", "matthew", "access",
	"yankees", "987654321", "dallas", "austin", "thunder",
	"taylor", "matrix", "admin", "test", "server",
	"changeme", "welcome", "password1", "password123",
	"P@ssword1", "P@ssw0rd", "Welcome1", "Welcome123",
	"Abcd1234", "Abcd!234", "P@ss1234", "Password1", "Password123",
	"Qwerty123", "Qwerty!1", "Admin123", "Admin!123", "Letmein123",
	"Test123!", "Test@123", "Summer2023", "Winter2023", "Spring2023",
	"Fall2023", "Company123", "Welcome!", "Pass1234", "Pass@1234",
	"Secret123", "Secret@123", "Temp1234", "Guest123", "Default123",
	"Hello123", "Hello@123", "qwerty123", "Qwerty123!", "abc123456",
	"pASSWORD", "Pa55w0rd", "pa55w0rd", "pa$$w0rd", "Passw0rd!",
	"iloveyou1", "princess1", "sunshine1", "football1", "charlie1",
	"dragon1", "monkey1", "master1", "qwerty1", "letmein1",
	"admin1", "root1", "test1", "guest1", "server1",
	"changeme1", "welcome1", "password2", "password12", "password1234",
	"pass123", "pass12345", "pass123456", "1234pass", "12345pass",
	"temp123", "temp1234", "temp12345", "temp123456", "test1234",
	"test12345", "test123456", "changeme123", "changeme1234", "changeme12345",
	"Welcome1234", "Welcome12345", "Welcome123456", "Admin1234", "Admin12345",
	"Admin123456", "P@ss1234!", "P@ssw0rd1", "P@ssw0rd12", "P@ssw0rd123",
	"Qwerty1234", "Qwerty12345", "Qwerty123456", "Abcd1234!", "Abcd12345",
	"Password1!", "Password1234", "Password12345", "Password123456", "Passw0rd1",
	"Passw0rd12", "Passw0rd123", "summer2023", "winter2023", "spring2023",
	"fall2023", "summer2024", "winter2024", "spring2024", "fall2024",
	"Company1234", "Company12345", "Company123456", "Hello1234", "Hello12345",
	"iloveyou12", "iloveyou123", "princess12", "princess123", "sunshine12",
	"sunshine123", "football12", "football123", "charlie12", "charlie123",
	"dragon12", "dragon123", "monkey12", "monkey123", "master12",
	"master123", "qwerty12", "qwerty1234", "letmein12", "letmein123",
	"admin12", "admin1234", "admin12345", "root12", "root123",
	"test12", "test12345", "guest12", "guest123", "server12",
	"server123", "changeme12", "changeme1234", "welcome12", "welcome1234",
	"password12", "password12345", "pass1234567", "pass12345678",
	"temp123456", "test1234567", "changeme123456", "Welcome123456",
	"Admin1234567", "P@ssw0rd1234", "Qwerty1234567", "Abcd123456",
	"Password1234567", "Passw0rd1234", "iloveyou1234", "princess1234",
	"sunshine1234", "football1234", "charlie1234", "dragon1234",
	"monkey1234", "master1234", "qwerty12345", "letmein1234",
	"admin123456", "root1234", "test123456", "guest1234", "server1234",
	"changeme12345", "welcome12345", "password12345678", "pass123456789",
	"temp1234567", "test12345678", "changeme1234567", "Welcome1234567",
	"Admin12345678", "P@ssw0rd12345", "Qwerty12345678", "Abcd1234567",
	"Password12345678", "Passw0rd12345", "iloveyou12345", "princess12345",
	"sunshine12345", "football12345", "charlie12345", "dragon12345",
	"monkey12345", "master12345", "qwerty123456", "letmein12345",
	"admin1234567", "root12345", "test123456789", "guest12345",
	"server12345", "changeme12345678", "welcome123456",
	"password123456789", "pass1234567890", "temp12345678",
	"test1234567890", "changeme123456789", "Welcome12345678",
	"Admin123456789", "P@ssw0rd123456", "Qwerty123456789",
	"Abcd12345678", "Password123456789", "Passw0rd123456",
	"iloveyou123456", "princess123456", "sunshine123456",
	"football123456", "charlie123456", "dragon123456",
	"monkey123456", "master123456", "qwerty1234567", "letmein123456",
	"admin12345678", "root123456", "test1234567890", "guest123456",
	"server123456", "changeme1234567890", "welcome1234567",
	"password1234567890", "pass12345678901", "temp123456789",
	"test12345678901", "changeme12345678901", "Welcome123456789",
	"Admin1234567890", "P@ssw0rd1234567", "Qwerty1234567890",
	"Abcd123456789", "Password1234567890", "Passw0rd1234567",
	"iloveyou1234567", "princess1234567", "sunshine1234567",
	"football1234567", "charlie1234567", "dragon1234567",
	"monkey1234567", "master1234567", "qwerty12345678", "letmein1234567",
	"admin123456789", "root1234567", "guest1234567", "server1234567",
	"changeme123456789", "welcome12345678",
	"password1234567890", "pass12345678901", "temp1234567890",
	"test12345678901", "changeme12345678901", "Welcome1234567890",
	"Admin12345678901", "P@ssw0rd12345678", "Qwerty12345678901",
	"Abcd1234567890", "Password12345678901", "Passw0rd12345678",
	"iloveyou12345678", "princess12345678", "sunshine12345678",
	"football12345678", "charlie12345678", "dragon12345678",
	"monkey12345678", "master12345678", "qwerty123456789",
	"letmein12345678", "admin1234567890", "root12345678",
	"guest12345678", "server12345678", "changeme1234567890",
	"welcome123456789", "password12345678901", "pass123456789012",
	"temp12345678901", "test123456789012", "changeme123456789012",
	"Welcome12345678901", "Admin123456789012", "P@ssw0rd123456789",
	"Qwerty123456789012", "Abcd12345678901", "Password123456789012",
	"Passw0rd123456789", "iloveyou123456789", "princess123456789",
	"sunshine123456789", "football123456789", "charlie123456789",
	"dragon123456789", "monkey123456789", "master123456789",
	"qwerty1234567890", "letmein123456789", "admin12345678901",
	"root123456789", "guest123456789", "server123456789",
	"changeme12345678901", "welcome1234567890",
	"password123456789012", "pass1234567890123", "temp123456789012",
	"test1234567890123", "changeme1234567890123", "Welcome123456789012",
	"Admin1234567890123", "P@ssw0rd1234567890", "Qwerty1234567890123",
	"Abcd123456789012", "Password1234567890123", "Passw0rd1234567890",
	"iloveyou1234567890", "princess1234567890", "sunshine1234567890",
	"football1234567890", "charlie1234567890", "dragon1234567890",
	"monkey1234567890", "master1234567890", "qwerty12345678901",
	"letmein1234567890", "admin123456789012", "root1234567890",
	"guest1234567890", "server1234567890", "changeme123456789012",
	"welcome12345678901", "password1234567890123",
	"pass12345678901234", "temp1234567890123", "test12345678901234",
	"changeme12345678901234", "Welcome1234567890123",
	"Admin12345678901234", "P@ssw0rd12345678901",
	"Qwerty12345678901234", "Abcd1234567890123",
	"Password12345678901234", "Passw0rd12345678901",
	"iloveyou12345678901", "princess12345678901",
	"sunshine12345678901", "football12345678901",
	"charlie12345678901", "dragon12345678901",
	"monkey12345678901", "master12345678901",
	"qwerty123456789012", "letmein12345678901",
	"admin1234567890123", "root12345678901",
	"guest12345678901", "server12345678901",
	"changeme1234567890123", "welcome123456789012",
	"password12345678901234", "pass123456789012345",
	"temp12345678901234", "test123456789012345",
	"changeme123456789012345", "Welcome12345678901234",
	"Admin123456789012345", "P@ssw0rd123456789012",
	"Qwerty123456789012345", "Abcd12345678901234",
	"Password123456789012345", "Passw0rd123456789012",
	"iloveyou123456789012", "princess123456789012",
	"sunshine123456789012", "football123456789012",
	"charlie123456789012", "dragon123456789012",
	"monkey123456789012", "master123456789012",
	"qwerty1234567890123", "letmein123456789012",
	"admin12345678901234", "root123456789012",
	"guest123456789012", "server123456789012",
	"changeme12345678901234", "welcome1234567890123",
	"password123456789012345", "pass1234567890123456",
	"temp123456789012345", "test1234567890123456",
	"changeme1234567890123456", "Welcome123456789012345",
	"Admin1234567890123456", "P@ssw0rd1234567890123",
	"Qwerty1234567890123456", "Abcd123456789012345",
	"Password1234567890123456", "Passw0rd1234567890123",
	"iloveyou1234567890123", "princess1234567890123",
	"sunshine1234567890123", "football1234567890123",
	"charlie1234567890123", "dragon1234567890123",
	"monkey1234567890123", "master1234567890123",
	"qwerty12345678901234", "letmein1234567890123",
	"admin123456789012345", "root1234567890123",
	"guest1234567890123", "server1234567890123",
	"changeme123456789012345", "welcome12345678901234",
	"password1234567890123456", "pass12345678901234567",
	"temp1234567890123456", "test12345678901234567",
	"changeme12345678901234567", "Welcome1234567890123456",
	"Admin12345678901234567", "P@ssw0rd12345678901234",
	"Qwerty12345678901234567", "Abcd1234567890123456",
	"Password12345678901234567", "Passw0rd12345678901234",
	"iloveyou12345678901234", "princess12345678901234",
	"sunshine12345678901234", "football12345678901234",
	"charlie12345678901234", "dragon12345678901234",
	"monkey12345678901234", "master12345678901234",
	"qwerty123456789012345", "letmein12345678901234",
	"admin1234567890123456", "root12345678901234",
	"guest12345678901234", "server12345678901234",
	"changeme1234567890123456", "welcome123456789012345",
	"password12345678901234567", "pass123456789012345678",
	"temp12345678901234567", "test123456789012345678",
	"changeme123456789012345678", "Welcome12345678901234567",
	"Admin123456789012345678", "P@ssw0rd123456789012345",
	"Qwerty123456789012345678", "Abcd12345678901234567",
	"Password123456789012345678", "Passw0rd123456789012345",
	"iloveyou123456789012345", "princess123456789012345",
	"sunshine123456789012345", "football123456789012345",
	"charlie123456789012345", "dragon123456789012345",
	"monkey123456789012345", "master123456789012345",
	"qwerty1234567890123456", "letmein123456789012345",
	"admin12345678901234567", "root123456789012345",
	"guest123456789012345", "server123456789012345",
	"changeme12345678901234567", "welcome1234567890123456",
}

var CommonUsernames = []string{
	"admin", "administrator", "root", "test", "guest",
	"user", "support", "sysadmin", "system", "operator",
	"manager", "webmaster", "info", "help", "service",
	"dev", "developer", "ops", "deploy", "backup",
	"oracle", "mysql", "postgres", "sa", "db2admin",
	"informix", "pgsql", "mongodb", "redis", "neo4j",
	"rabbitmq", "elastic", "kibana", "logstash",
	"ftp", "anonymous", "nobody", "daemon", "bin",
	"www", "http", "mail", "postfix", "sendmail",
	"apache", "nginx", "tomcat", "jenkins", "git",
	"gitlab", "bitbucket", "svn", "ci", "cd",
	"build", "release", "staging", "production",
	"monitor", "nagios", "grafana", "prometheus", "zabbix",
	"jira", "confluence", "teamcity", "bamboo",
	"sonar", "nexus", "artifactory", "registry", "harbor",
	"k8s", "kubernetes", "docker", "minio", "s3",
	"vault", "consul", "etcd", "zookeeper", "kafka",
	"activemq", "nats", "mqtt", "amqp",
	"ntp", "snmp", "ldap", "kerberos", "radius",
	"tacacs", "squid", "haproxy", "varnish", "traefik",
	"caddy", "istio", "envoy", "linkerd",
	"webmin", "cpanel", "whm", "plesk", "ispconfig",
	"postmaster", "hostmaster", "webhost", "abuse",
	"noc", "security", "audit", "compliance", "Incident",
	"nocadmin", "sysop", "moderator", "editor", "author",
	"subscriber", "member", "client", "customer", "partner",
	"vendor", "supplier", "contractor", "consultant", "freelancer",
	"intern", "trainee", "apprentice", "junior", "senior",
	"lead", "principal", "staff", "fellow", "distinguished",
	"cto", "cio", "ceo", "cfo", "coo",
	"vp", "director", "head", "chief", "officer",
	"analyst", "engineer", "architect", "designer", "researcher",
	"scientist", "programmer", "coder", "hacker", "cracker",
	"phreaker", "script kiddie", "lamer", "newbie", "noob",
	"rootkit", "backdoor", "trojan", "virus", "worm",
	"spyware", "adware", "malware", "ransomware", "cryptominer",
	"botnet", "zombie", "mule", "handler", "operator",
	"controller", "master", "slave", "client", "server",
	"proxy", "relay", "bridge", "hub", "switch",
	"router", "firewall", "gateway", "modem", "accesspoint",
	"repeater", "extender", "booster", "amplifier", "antenna",
	"tower", "mast", "pole", "cable", "wire",
	"fiber", "copper", "coax", "twisted", "pair",
	"ethernet", "wifi", "bluetooth", "nfc", "rfid",
	"zigbee", "zwave", "lora", "sigfox", "nb-iot",
	"lte", "5g", "6g", "satellite", "mesh",
}

var DirectoryWordlist = []string{
	"admin", "login", "wp-admin", "wp-login", "administrator",
	"cpanel", "webmail", "phpmyadmin", "myadmin", "mysql",
	"db", "database", "phpinfo", "info", "test",
	"debug", "console", "dashboard", "panel", "portal",
	"manager", "management", "api", "v1", "v2",
	"graphql", "swagger", "docs", "documentation", "help",
	"support", "contact", "about", "blog", "news",
	"forum", "community", "wiki", "chat", "messages",
	"mail", "email", "smtp", "pop", "imap",
	"ftp", "sftp", "ssh", "rdp", "vnc",
	".env", ".git", ".svn", ".hg", ".DS_Store",
	"robots.txt", "sitemap.xml", "crossdomain.xml", "clientaccesspolicy.xml",
	".htaccess", ".htpasswd", ".htgroups", ".htpasswd.bak",
	"wp-config.php", "wp-config.php.bak", "wp-config.php.old",
	"config.php", "config.php.bak", "config.inc.php",
	"database.yml", "database.yml.bak", "config.yml",
	".git/HEAD", ".git/config", ".git/logs/HEAD",
	"backup", "backups", "bak", "old", "temp",
	"tmp", "cache", "logs", "log", "debug.log",
	"error.log", "access.log", "nginx.conf", "apache.conf",
	".bash_history", ".ssh/authorized_keys", ".ssh/id_rsa",
	"id_rsa", "id_rsa.pub", "authorized_keys", "known_hosts",
	"etc/passwd", "etc/shadow", "etc/hosts",
	"proc/self/environ", "proc/version", "proc/cmdline",
	"wp-content/uploads", "wp-includes", "wp-content/plugins",
	"wp-content/themes", "uploads", "files", "media",
	"assets", "static", "images", "img", "css",
	"js", "scripts", "fonts", "icons", "downloads",
	"src", "source", "lib", "vendor", "node_modules",
	"bower_components", ".bower", "package.json", "composer.json",
	"Gemfile", "requirements.txt", "Pipfile", "go.mod",
	"Dockerfile", "docker-compose.yml", "docker-compose.yaml",
	"Makefile", "Rakefile", "Gruntfile", "Gulpfile",
	".travis.yml", "Jenkinsfile", ".circleci", ".github",
	"bitbucket-pipelines.yml", "azure-pipelines.yml",
	".env", ".env.local", ".env.production", ".env.staging",
	".env.development", ".env.example", ".env.bak",
	"config.json", "config.yaml", "config.xml",
	"settings.json", "settings.yaml", "settings.xml",
	"application.properties", "application.yml",
	"web.config", "appsettings.json", "appsettings.Development.json",
	".well-known/security.txt", "security.txt",
	"favicon.ico", "humans.txt", "manifest.json",
	"swagger.json", "swagger.yaml", "openapi.json", "openapi.yaml",
	"graphql", "graphiql", "playground", "altair",
	"vendor/phpunit", "vendor/composer", "vendor/autoload.php",
	"cgi-bin", "scripts", "msadc", "scripts/iisadmin",
	"examples", "sample", "samples",
	"_vti_bin", "_vti_cnf", "_vti_log", "_vti_pvt",
	"_vti_inf", "_vti_txt", "MSADC",
	"owa", "exchange", "autodiscover", "EWS",
	"Microsoft-Server-ActiveSync", "Sync",
	"ecp", "powershell", "aspnet_client",
	"remote", "gateway", "vpn", "citrix",
	"rdweb", "feed", "rss", "atom", "xmlrpc.php",
	"wp-cron.php", "wp-links-opml.php", "wp-login.php",
	"readme.html", "license.txt", "readme.txt",
	"RELEASE_NOTES", "CHANGELOG", "CHANGES", "HISTORY",
	"INSTALL", "README", "TODO", "BUGS",
	"SECURITY", "CONTRIBUTING", "AUTHORS", "COPYING",
	".gitignore", ".gitattributes", ".editorconfig",
	"jest.config", "tsconfig.json", "webpack.config",
	"babel.config", ".babelrc", ".eslintrc", ".prettierrc",
	"phpunit.xml", "phpcs.xml", "phpstan.neon",
	"Vagrantfile", "Berksfile", "Policyfile",
	"terraform.tfstate", "terraform.tfvars", "variables.tf",
	"main.tf", "outputs.tf", "providers.tf",
	"kubernetes.yaml", "helmfile.yaml", "Chart.yaml",
	"values.yaml", "Dockerfile.dev", "Dockerfile.prod",
	"docker-compose.dev.yml", "docker-compose.prod.yml",
	"actuator", "actuator/env", "actuator/health",
	"actuator/info", "actuator/mappings", "actuator/beans",
	"actuator/configprops", "actuator/metrics", "actuator/trace",
	"trace", "metrics", "beans", "env", "mappings",
	"heapdump", "threaddump", "jolokia", "prometheus",
	"server-info", "server-status", "nginx_status",
	"server-status", "mod_status", "fpm-status",
	"php-fpm", "phpinfo.php", "test.php", "info.php",
	"shell.php", "cmd.php", "c99.php", "r57.php",
	"webshell.php", "backdoor.php", "hack.php", "evil.php",
	"administrator/", "manager/html", "manager/status",
	"manager/text", "manager/jmxproxy", "manager/start",
	"manager/stop", "host-manager/html", "host-manager/text",
	"hudson", "jenkins", "bamboo", "teamcity",
	"sonar", "sonarqube", "nexus", "nexus3",
	"artifactory", "harbor", "registry",
	"kibana", "grafana", "prometheus", "zabbix",
	"nagios", "cacti", "mrtg", "munin",
	"sensu", "datadog", "newrelic", "appdynamics",
}

var SubdomainWordlist = []string{
	"www", "mail", "ftp", "smtp", "pop", "imap", "webmail",
	"mx", "ns1", "ns2", "ns3", "ns4", "dns", "dns1", "dns2",
	"vpn", "remote", "gateway", "router", "firewall", "proxy",
	"api", "dev", "staging", "test", "beta", "alpha", "demo",
	"admin", "portal", "dashboard", "panel", "cpanel", "webmin",
	"git", "gitlab", "github", "bitbucket", "svn", "repo",
	"ci", "cd", "jenkins", "travis", "drone", "build",
	"db", "database", "mysql", "postgres", "mongo", "redis",
	"elastic", "kibana", "grafana", "prometheus", "nagios",
	"app", "mobile", "m", "wap", "touch",
	"shop", "store", "cart", "checkout", "pay",
	"blog", "forum", "community", "wiki", "help", "support",
	"cdn", "static", "assets", "media", "images", "img",
	"ns", "mx1", "mx2", "mx3", "autodiscover", "autoconfig",
	"imap", "pop3", "smtps", "submission",
	"intranet", "extranet", "internal", "external",
	"backup", "bak", "old", "archive", "legacy",
	"monitor", "status", "health", "ping", "check",
	"log", "logs", "syslog", "elk",
	"auth", "sso", "oauth", "ldap", "ad", "dc",
	"k8s", "kubernetes", "docker", "registry", "harbor",
	"minio", "s3", "blob", "storage",
	"rabbitmq", "kafka", "zookeeper", "etcd", "consul",
	"vault", "pki", "cert", "ca", "ssl",
	"ntp", "ntp1", "ntp2", "time",
	"ldaps", "kerberos", "kdc",
	"dr", "disaster", "recovery",
	"webdisk", "whm",
	"phpmyadmin", "pma", "myadmin",
	"web", "edge",
	"edge1", "edge2", "lb", "loadbalancer",
	"haproxy", "nginx", "apache", "httpd",
	"tomcat", "jboss", "wildfly", "weblogic",
	"was", "ihs", "domino", "lotus",
	"owa", "ews",
	"activesync", "mapi", "pop3", "imap4",
	"sharepoint", "onedrive", "teams", "skype",
	"lync", "lyncdiscover", "meet", "join",
	"webinar", "conf", "conference", "meetings",
	"staging", "stage", "dev", "development",
	"uat", "qa", "quality", "testing",
	"prod", "production", "live",
	"preprod", "pre-prod", "preproduction",
	"canary", "rc", "release", "ga",
	"nightly", "daily", "weekly", "monthly",
	"feature", "feature1", "feature2",
	"sandbox", "playground", "lab", "experiment",
	"demo", "demos", "showcase", "example",
	"docs", "documentation", "wiki", "help",
	"kb", "knowledge", "support", "faq",
	"forum", "community", "discuss", "talk",
	"chat", "messaging", "im", "irc",
	"search", "find", "lookup",
	"auth", "login", "signin", "signup",
	"register", "account", "profile", "settings",
	"billing", "payment", "invoice", "order",
	"cart", "checkout", "pay", "purchase",
	"shop", "store", "mall", "market",
	"cdn", "media", "static", "assets",
	"img", "image", "images", "photo", "photos",
	"video", "videos", "audio", "music",
	"download", "downloads", "upload", "uploads",
	"file", "files", "document", "documents",
	"backup", "backups", "bak", "archive",
	"old", "legacy", "v1", "v2", "v3",
	"internal", "intranet", "extranet",
	"private", "secure", "protected",
	"public", "open", "guest",
	"test", "testing", "tests", "qa",
	"dev", "development", "debug", "staging",
	"stage", "uat", "preprod", "pre-prod",
	"prod", "production", "live", "release",
	"canary", "rc", "ga", "stable",
	"nightly", "daily", "weekly", "monthly",
	"feature", "sandbox", "playground", "lab",
}

var ParameterWordlist = []string{
	"id", "user", "uid", "username", "login", "pass", "password",
	"pwd", "token", "key", "api_key", "apikey", "secret",
	"email", "name", "first_name", "last_name", "phone",
	"url", "uri", "redirect", "redirect_uri", "return",
	"return_to", "next", "continue", "goto", "ref",
	"page", "p", "q", "query", "search",
	"cmd", "command", "action", "method", "function",
	"file", "path", "dir", "directory", "folder",
	"limit", "offset", "start", "end",
	"sort", "order", "order_by", "sort_by", "column",
	"type", "format", "output", "response", "callback",
	"json", "xml", "csv", "html", "text",
	"debug", "test", "verbose", "quiet", "silent",
	"lang", "locale", "language", "i18n", "l10n",
	"csrf", "csrf_token", "_token", "nonce",
	"timestamp", "date", "time", "year", "month",
	"day", "hour", "minute", "second", "tz",
	"category", "tag", "filter", "status",
	"state", "mode", "version", "v", "api_version",
	"fields", "include", "exclude", "expand", "select",
	"page_size", "per_page", "max_results", "count", "total",
	"hash", "md5", "sha1", "sha256", "signature",
	"sign", "verify", "validate", "check", "confirm",
	"accept", "decline", "cancel", "close", "open",
	"enable", "disable", "activate", "deactivate", "delete",
	"remove", "add", "create", "update", "edit",
	"save", "store", "destroy", "purge", "flush",
	"reset", "clear", "wipe", "nuke", "drop",
	"webhook", "notify", "alert", "ping",
	"host", "server", "port", "protocol", "scheme",
	"ssl", "tls", "cert", "ca",
	"auth", "authorization", "credentials", "bearer", "oauth",
	"grant_type", "client_id", "client_secret", "scope",
	"code", "access_token", "refresh_token", "expires_in", "token_type",
	"from", "to", "cc", "bcc", "subject",
	"body", "message", "content", "data",
	"payload", "params", "args", "options", "config",
	"setting", "preference", "flag", "switch",
	"result", "error", "warning", "info", "success",
	"fail", "denied", "denied", "forbidden",
	"page", "offset", "cursor", "next_token", "prev_token",
	"limit", "size", "max", "min", "range",
	"lat", "lon", "latitude", "longitude", "geo",
	"radius", "distance", "unit", "metric", "imperial",
	"currency", "amount", "price", "cost", "discount",
	"coupon", "promo", "voucher", "code",
	"transaction", "payment", "refund", "charge",
	"subscription", "plan", "tier", "level", "status",
	"active", "inactive", "pending", "suspended", "banned",
	"verified", "unverified", "confirmed", "unconfirmed",
	"role", "permission", "group", "org", "tenant",
	"scope", "context", "environment", "region", "zone",
	"cluster", "node", "instance", "container", "pod",
	"service", "endpoint", "route", "method", "path",
	"version", "api_version", "v", "rev", "revision",
	"format", "encoding", "charset", "content_type",
	"accept", "cache", "etag", "if_none_match",
	"if_modified_since", "if_match", "if_unmodified_since",
	"range", "content_range", "content_length",
}

var BackupExtensions = []string{
	".bak", ".old", ".orig", ".swp", ".swo",
	".save", ".tmp", ".temp", ".backup", ".back",
	".copy", ".save1", ".save2", ".save3",
	".1", ".2", ".3", ".4", ".5",
	".6", ".7", ".8", ".9",
	".dist", ".sample", ".example", ".default",
	".disabled", ".inactive", ".off", ".old1",
	".old2", ".old3", ".bak1", ".bak2", ".bak3",
	".sav", ".saved", ".prev", ".previous",
	".current", ".new", ".latest", ".last",
	".owntmp", ".php", ".php.bak", ".php.old",
	".php~", ".php.swp", ".php.inc", ".inc",
	".inc.bak", ".inc.old", ".inc.swp",
	".conf", ".conf.bak", ".conf.old", ".conf.swp",
	".cfg", ".cfg.bak", ".cfg.old", ".cfg.swp",
	".ini", ".ini.bak", ".ini.old", ".ini.swp",
	".xml", ".xml.bak", ".xml.old", ".xml.swp",
	".json", ".json.bak", ".json.old", ".json.swp",
	".yml", ".yml.bak", ".yml.old", ".yml.swp",
	".yaml", ".yaml.bak", ".yaml.old", ".yaml.swp",
	".sql", ".sql.bak", ".sql.old", ".sql.gz",
	".sql.dump", ".dump", ".export", ".import",
	".tar", ".tar.gz", ".tgz", ".zip", ".rar",
	".7z", ".bz2", ".gz", ".xz", ".zst",
	"~", ".~", ".bak~", ".old~", ".orig~",
	".save~", ".tmp~", ".swp~", ".swo~",
}

var SensitiveFiles = []string{
	".env", ".env.local", ".env.production", ".env.staging",
	".env.development", ".env.backup", ".env.old", ".env.example",
	".git/config", ".git/HEAD", ".git/index", ".git/logs/HEAD",
	".gitignore", ".gitattributes", ".gitmodules",
	".svn/entries", ".svn/wc.db", ".svn/format",
	".hg/store", ".hgignore", ".hgtags",
	".htpasswd", ".htaccess", ".htgroups",
	".ssh/authorized_keys", ".ssh/id_rsa", ".ssh/id_rsa.pub",
	".ssh/id_dsa", ".ssh/id_dsa.pub", ".ssh/id_ecdsa",
	".ssh/id_ecdsa.pub", ".ssh/id_ed25519", ".ssh/id_ed25519.pub",
	".ssh/config", ".ssh/known_hosts",
	".bash_history", ".zsh_history", ".fish_history",
	".bashrc", ".bash_profile", ".bash_login", ".bash_logout",
	".profile", ".zshrc", ".zprofile", ".zlogin",
	".vimrc", ".emacs", ".nanorc",
	".netrc", ".pgpass", ".my.cnf", ".mylogin.cnf",
	"wp-config.php", "wp-config.php.bak", "wp-config.php.old",
	"config.php", "config.php.bak", "config.php.old",
	"configuration.php", "configuration.php.bak",
	"settings.php", "settings.php.bak",
	"database.yml", "database.yml.bak",
	"config.yml", "config.yml.bak",
	"config.json", "config.json.bak",
	"config.xml", "config.xml.bak",
	"application.properties", "application.properties.bak",
	"application.yml", "application.yml.bak",
	"web.config", "web.config.bak",
	"appsettings.json", "appsettings.json.bak",
	".aws/credentials", ".aws/config",
	".azure/accessTokens.json", ".azure/azureProfile.json",
	".gcloud/credentials.db", ".gcloud/properties",
	".dockercfg", ".docker/config.json",
	"credentials.json", "service-account.json",
	"keyfile.json", "client_secret.json",
	"id_rsa", "id_rsa.pub", "id_dsa", "id_dsa.pub",
	"id_ecdsa", "id_ecdsa.pub", "id_ed25519", "id_ed25519.pub",
	"*.pem", "*.key", "*.crt", "*.cer", "*.p12",
	"*.pfx", "*.jks", "*.keystore", "*.truststore",
	"*.key.pem", "*.cert.pem", "*.chain.pem",
	"shadow", "passwd", "group", "gshadow",
	"sudoers", "sudoers.d", "doas.conf",
	"crontab", "crontab.bak", "at.allow", "at.deny",
	"hosts.allow", "hosts.deny", "hosts.equiv",
	"resolv.conf", "nsswitch.conf", "pam.conf",
	"fstab", "mtab", "crypttab",
	".dockerignore", ".npmrc", ".pypirc", ".gem/credentials",
	".cargo/credentials", ".cargo/config",
	"database.sql", "database.sql.bak", "dump.sql",
	"backup.sql", "backup.sql.gz", "data.sql",
	"seed.sql", "schema.sql", "migration.sql",
	"docker-compose.yml", "docker-compose.yaml",
	"docker-compose.override.yml", "docker-compose.prod.yml",
	"Vagrantfile", "Berksfile", "Policyfile",
	".terraform.tfstate", ".terraform.tfstate.backup",
	"terraform.tfstate", "terraform.tfstate.backup",
	"terraform.tfvars", "terraform.tfvars.example",
	"kubernetes.yaml", "kubeconfig", "kubectl.yaml",
	".kube/config", "kube-config.yaml",
	"secrets.yaml", "secrets.yml", "secrets.json",
	"credentials.yml", "credentials.yaml", "credentials.json",
	"service-account.json", "key.json", "private-key.pem",
}

var DefaultCreds = []string{
	"admin:admin", "admin:password", "root:root", "root:toor",
	"root:password", "root:123456", "admin:123456", "admin:admin123",
	"admin:password123", "root:admin", "root:changeme", "admin:changeme",
	"admin:welcome", "root:welcome", "admin:test", "root:test",
	"guest:guest", "user:user", "test:test", "admin:root",
	"oracle:oracle", "postgres:postgres", "mysql:mysql", "msfadmin:msfadmin",
	"ftp:ftp", "user:password", "admin:1234", "root:root123",
	"admin:admin@123", "root:P@ssw0rd", "admin:P@ssw0rd", "root:Passw0rd",
	"admin:Passw0rd", "administrator:administrator", "administrator:password",
	"sa:sa", "sa:password", "sa:", "db2admin:db2admin",
	"informix:informix", "pgsql:pgsql", "mongodb:mongodb",
	"redis:", "neo4j:neo4j", "rabbitmq:guest",
	"elastic:changeme", "kibana:changeme", "logstash:changeme",
	"tomcat:tomcat", "tomcat:s3cret", "tomcat:admin",
	"weblogic:weblogic", "weblogic:Oracle@123", "weblogic:welcome1",
	"glassfish:glassfish", "glassfish:admin", "jboss:jboss", "jboss:admin",
	"jenkins:jenkins", "jenkins:admin", "gitlab:root", "gitlab:password",
	"gerrit:gerrit", "gerrit:admin", "sonarqube:admin",
	"nexus:admin", "admin:admin1234", "admin:admin@1234",
	"admin:letmein", "admin:welcome1", "admin:P@ssw0rd1",
	"admin:password1", "admin:password!", "admin:admin!",
	"root:password!", "root:letmein", "root:welcome1",
	"user:user123", "test:test123", "guest:guest123",
	"demo:demo", "demo:password", "demo:demo123",
	"sample:sample", "sample:password", "public:public",
	"private:private", "secure:secure", "secret:secret",
	"root:123", "root:1234", "root:12345", "root:123456",
	"admin:123", "admin:1234", "admin:12345", "admin:123456",
	"user:123", "user:1234", "user:12345", "user:123456",
	"test:123", "test:1234", "test:12345", "test:123456",
	"guest:123", "guest:1234", "guest:12345", "guest:123456",
	"root:qwerty", "admin:qwerty", "user:qwerty", "test:qwerty",
	"root:abc123", "admin:abc123", "user:abc123", "test:abc123",
	"root:passw0rd", "admin:passw0rd", "user:passw0rd", "test:passw0rd",
	"root:P@ssw0rd!", "admin:P@ssw0rd!", "user:P@ssw0rd!",
	"root:Password1", "admin:Password1", "user:Password1", "test:Password1",
	"root:Password123", "admin:Password123", "user:Password123",
	"root:P@ssword1", "admin:P@ssword1", "user:P@ssword1",
	"root:Welcome1", "admin:Welcome1", "user:Welcome1",
	"root:Welcome123", "admin:Welcome123", "user:Welcome123",
	"root:Summer2023", "admin:Summer2023", "user:Summer2023",
	"root:Winter2023", "admin:Winter2023", "user:Winter2023",
	"root:Spring2023", "admin:Spring2023", "user:Spring2023",
	"root:Fall2023", "admin:Fall2023", "user:Fall2023",
	"root:Company123", "admin:Company123", "user:Company123",
	"root:Welcome!", "admin:Welcome!", "user:Welcome!",
	"root:Hello123", "admin:Hello123", "user:Hello123",
	"root:Hello@123", "admin:Hello@123", "user:Hello@123",
	"root:qwerty123", "admin:qwerty123", "user:qwerty123",
	"root:abc123456", "admin:abc123456", "user:abc123456",
	"cisco:cisco", "admin:cisco", "cisco:admin",
	"ubnt:ubnt", "admin:ubnt", "ubnt:admin",
	"admin:admin12345", "admin:admin123456",
	"pi:raspberry", "pi:raspberryberry",
	"admin:aircontrol2007", "ubnt:ubnt",
	"admin:password1234", "root:password1234",
	"admin:password12345", "root:password12345",
	"admin:password123456", "root:password123456",
	"admin:Passw0rd1", "admin:Passw0rd12",
	"admin:Passw0rd123", "admin:P@ssw0rd1234",
	"admin:Qwerty123", "admin:Qwerty1234",
	"admin:Qwerty12345", "admin:Qwerty123456",
	"admin:Summer2024", "admin:Winter2024",
	"admin:Spring2024", "admin:Fall2024",
	"admin:Summer2023", "admin:Winter2023",
	"admin:Spring2023", "admin:Fall2023",
	"root:Summer2024", "root:Winter2024",
	"root:Spring2024", "root:Fall2024",
	"user:Summer2024", "user:Winter2024",
	"user:Spring2024", "user:Fall2024",
	"guest:Summer2024", "guest:Winter2024",
	"guest:Spring2024", "guest:Fall2024",
	"test:Summer2024", "test:Winter2024",
	"test:Spring2024", "test:Fall2024",
	"admin:Summer2023", "admin:Winter2023",
	"admin:Spring2023", "admin:Fall2023",
	"root:Summer2023", "root:Winter2023",
	"root:Spring2023", "root:Fall2023",
	"user:Summer2023", "user:Winter2023",
	"user:Spring2023", "user:Fall2023",
	"guest:Summer2023", "guest:Winter2023",
	"guest:Spring2023", "guest:Fall2023",
	"test:Summer2023", "test:Winter2023",
	"test:Spring2023", "test:Fall2023",
	"admin:admin@12345", "admin:admin@123456",
	"admin:admin1234567", "admin:admin12345678",
	"admin:admin123456789", "admin:admin1234567890",
	"root:root1234567890", "root:root123456789",
	"root:root12345678", "root:root1234567",
	"root:root123456", "root:root12345",
	"root:root1234", "root:root123",
	"user:user1234567890", "user:user123456789",
	"user:user12345678", "user:user1234567",
	"user:user123456", "user:user12345",
	"user:user1234", "user:user123",
	"guest:guest1234567890", "guest:guest123456789",
	"guest:guest12345678", "guest:guest1234567",
	"guest:guest123456", "guest:guest12345",
	"guest:guest1234", "guest:guest123",
	"test:test1234567890", "test:test123456789",
	"test:test12345678", "test:test1234567",
	"test:test123456", "test:test12345",
	"test:test1234", "test:test123",
	"admin:P@ssw0rd1234", "admin:P@ssw0rd12345",
	"admin:P@ssw0rd123456", "admin:P@ssw0rd1234567",
	"admin:P@ssw0rd12345678", "admin:P@ssw0rd123456789",
	"admin:P@ssw0rd1234567890", "admin:P@ssword12345",
	"admin:P@ssword123456", "admin:P@ssword1234567",
	"admin:Password12345", "admin:Password123456",
	"admin:Password1234567", "admin:Password12345678",
	"admin:Password123456789", "admin:Password1234567890",
	"admin:Welcome12345", "admin:Welcome123456",
	"admin:Welcome1234567", "admin:Welcome12345678",
	"admin:Welcome123456789", "admin:Welcome1234567890",
}

var APIEndpoints = []string{
	"/api", "/api/v1", "/api/v2", "/api/v3",
	"/api/internal", "/api/external", "/api/public", "/api/private",
	"/api/admin", "/api/user", "/api/users", "/api/auth",
	"/api/login", "/api/logout", "/api/register", "/api/signup",
	"/api/token", "/api/refresh", "/api/revoke",
	"/api/profile", "/api/account", "/api/settings",
	"/api/config", "/api/health", "/api/status", "/api/info",
	"/api/version", "/api/metrics", "/api/stats",
	"/api/search", "/api/query", "/api/filter",
	"/api/data", "/api/export", "/api/import", "/api/upload",
	"/api/download", "/api/files", "/api/documents", "/api/images",
	"/api/media", "/api/assets", "/api/resources",
	"/api/products", "/api/items", "/api/orders", "/api/cart",
	"/api/checkout", "/api/payment", "/api/billing", "/api/invoice",
	"/api/subscription", "/api/plans", "/api/pricing",
	"/api/customers", "/api/clients", "/api/partners",
	"/api/vendors", "/api/suppliers", "/api/contracts",
	"/api/projects", "/api/tasks", "/api/issues", "/api/tickets",
	"/api/comments", "/api/reviews", "/api/ratings",
	"/api/notifications", "/api/messages", "/api/alerts",
	"/api/logs", "/api/audit", "/api/events", "/api/webhooks",
	"/api/robots.txt", "/api/sitemap.xml",
	"/rest", "/rest/api", "/rest/v1", "/rest/v2",
	"/graphql", "/graphiql", "/playground",
	"/swagger", "/swagger.json", "/swagger.yaml", "/swagger-ui",
	"/openapi", "/openapi.json", "/openapi.yaml",
	"/docs", "/redoc", "/documentation",
	"/.well-known/openid-configuration", "/.well-known/oauth-authorization-server",
	"/.well-known/jwks.json", "/.well-known/change-password",
	"/oauth", "/oauth/authorize", "/oauth/token", "/oauth/revoke",
	"/oauth/callback", "/oauth/consent",
	"/oidc", "/oidc/authorize", "/oidc/token", "/oidc/userinfo",
	"/saml", "/saml/acs", "/saml/sso",
	"/cas", "/cas/login", "/cas/logout", "/cas/validate",
	"/webhook", "/webhooks", "/callback", "/callbacks",
	"/push", "/notify", "/events", "/stream",
	"/batch", "/bulk", "/async", "/job", "/jobs",
	"/queue", "/tasks", "/workers",
	"/health", "/health/live", "/health/ready", "/health/heartbeat",
	"/readiness", "/liveness", "/startup",
	"/metrics", "/prometheus", "/stats", "/statistics",
	"/debug", "/debug/pprof", "/debug/vars", "/debug/requests",
	"/trace", "/traces", "/spans",
	"/config", "/env", "/env.json", "/env.js",
	"/admin", "/admin/dashboard", "/admin/api",
	"/management", "/mgmt", "/sys", "/system",
}

var GraphQLWords = []string{
	"__schema", "__type", "__typename", "__isDeprecated",
	"__deprecatedReason", "__enumValues", "__inputFields",
	"__interfaces", "__kind", "__name", "__ofType",
	"__possibleTypes", "__specifiedByURL",
	"query", "mutation", "subscription", "fragment",
	"on", "true", "false", "null",
	"Int", "Float", "String", "Boolean", "ID",
	"__InputValue", "__Field", "__TypeKind",
	"OBJECT", "INTERFACE", "UNION", "ENUM", "INPUT_OBJECT",
	"SCALAR", "LIST", "NON_NULL",
	"user", "users", "me", "viewer", "currentUser",
	"node", "nodes", "edges", "pageInfo", "cursor",
	"totalCount", "hasNextPage", "hasPreviousPage",
	"first", "last", "before", "after",
	"login", "logout", "signup", "register",
	"createUser", "updateUser", "deleteUser",
	"createPost", "updatePost", "deletePost",
	"createComment", "updateComment", "deleteComment",
	"createMutation", "updateMutation", "deleteMutation",
	"findMany", "findOne", "findUnique",
	"findFirst", "findLast", "count",
	"aggregate", "groupBy", "distinct",
	"orderBy", "where", "include", "select",
	"data", "errors", "extensions", "locations",
	"message", "path", "extensions", "code",
	"argument", "defaultValue", "description",
	"enumValues", "fields", "inputFields",
	"interfaces", "isDeprecated", "kind",
	"name", "ofType", "possibleTypes", "specifiedByURL",
	"type", "types",
}

var CloudEndpoints = []string{
	"/metadata", "/metadata/instance", "/metadata/instance/identity",
	"/metadata/instance/compute", "/metadata/instance/network",
	"/metadata/instance/disks", "/metadata/instance/external",
	"/metadata/instance/internal", "/metadata/instance/azure",
	"/metadata/instance/security", "/metadata/instance/management",
	"/metadata/instance/osProfile", "/metadata/instance/storageProfile",
	"/metadata/instance/networkProfile", "/metadata/instance/diagnosticsProfile",
	"/metadata/identity", "/metadata/identity/oauth2/token",
	"/metadata/identity/token", "/metadata/identity/clientId",
	"/metadata/token", "/metadata/token/oauth2",
	"/computeMetadata/v1", "/computeMetadata/v1/project",
	"/computeMetadata/v1/instance", "/computeMetadata/v1/instance/hostname",
	"/computeMetadata/v1/instance/id", "/computeMetadata/v1/instance/zone",
	"/computeMetadata/v1/instance/hostname", "/computeMetadata/v1/instance/service-accounts",
	"/computeMetadata/v1/instance/service-accounts/default/token",
	"/latest/meta-data", "/latest/meta-data/iam", "/latest/meta-data/iam/security-credentials",
	"/latest/meta-data/instance-id", "/latest/meta-data/public-keys",
	"/latest/meta-data/hostname", "/latest/meta-data/local-ipv4",
	"/latest/meta-data/public-ipv4", "/latest/meta-data/ami-id",
	"/latest/meta-data/ami-launch-index", "/latest/meta-data/ami-manifest-path",
	"/latest/meta-data/block-device-mapping", "/latest/meta-data/events",
	"/latest/meta-data/placement", "/latest/meta-data/placement/availability-zone",
	"/latest/meta-data/placement/region", "/latest/dynamic/instance-identity/document",
	"/buckets", "/buckets/{bucket}", "/buckets/{bucket}/objects",
	"/storage/v1/b", "/storage/v1/b/{bucket}",
	"/storage/v1/b/{bucket}/o", "/storage/v1/b/{bucket}/o/{object}",
	"/storage/v1/b/{bucket}/iam", "/storage/v1/b/{bucket}/defaultObjectAcl",
	"/storage/v1/b/{bucket}/acl", "/storage/v1/b/{bucket}/cors",
	"/storage/v1/b/{bucket}/lifecycle", "/storage/v1/b/{bucket}/location",
	"/storage/v1/b/{bucket}/logging", "/storage/v1/b/{bucket}/notification",
	"/storage/v1/b/{bucket}/policy", "/storage/v1/b/{bucket}/versioning",
	"/storage/v1/b/{bucket}/website", "/storage/v1/b/{bucket}/bindings",
	"/storage/v1/b/{bucket}/bindings/{entity}",
	"/blob", "/blob/{container}", "/blob/{container}/{blob}",
	"/queue", "/queue/{queue}", "/queue/messages",
	"/servicebus", "/servicebus/{namespace}",
}

var WordPressPaths = []string{
	"/wp-admin/", "/wp-login.php", "/wp-login.php?action=register",
	"/wp-admin/admin-ajax.php", "/wp-admin/install.php",
	"/wp-admin/setup-config.php", "/wp-admin/upgrade.php",
	"/wp-cron.php", "/wp-links-opml.php", "/wp-mail.php",
	"/xmlrpc.php", "/xmlrpc.php?rsd", "/wp-trackback.php",
	"/feed/", "/comments/feed/", "/?feed=rss2",
	"/wp-content/", "/wp-includes/",
	"/wp-content/plugins/", "/wp-content/themes/",
	"/wp-content/uploads/", "/wp-content/upgrade/",
	"/wp-content/cache/", "/wp-content/backups/",
	"/wp-content/debug.log", "/wp-content/uploads/",
	"/wp-content/plugins/index.php", "/wp-content/themes/index.php",
	"/wp-content/uploads/index.php",
	"/wp-json/", "/wp-json/wp/v2/users", "/wp-json/wp/v2/posts",
	"/wp-json/wp/v2/pages", "/wp-json/wp/v2/comments",
	"/wp-json/wp/v2/categories", "/wp-json/wp/v2/tags",
	"/wp-json/wp/v2/media", "/wp-json/wp/v2/settings",
	"/wp-json/wp/v2/search", "/wp-json/wp/v2/types",
	"/wp-json/wp/v2/taxonomies", "/wp-json/wp/v2/blockTypes",
	"/wp-json/wp/v2/template-parts", "/wp-json/wp/v2/templates",
	"/wp-json/wp/v2/global-styles", "/wp-json/wp/v2/patterns",
	"/wp-json/wp/v2/sidebars", "/wp-json/wp/v2/widgets",
	"/wp-json/wp/v2/menu-items", "/wp-json/wp/v2/menus",
	"/wp-json/wp/v2/blocks", "/wp-json/wp/v2/block-revisions",
	"/wp-json/wc/v3/", "/wp-json/wc/v3/orders",
	"/wp-json/wc/v3/products", "/wp-json/wc/v3/customers",
	"/wp-json/wc/v3/coupons", "/wp-json/wc/v3/reports",
	"/wp-json/wc/v2/", "/wp-json/wc/v2/orders",
	"/wp-json/wc/v2/products", "/wp-json/wc/v2/customers",
	"/xmlrpc.php?xmlrpc=true", "/xmlrpc.php?wsdl",
	"/wp-admin/export.php", "/wp-admin/import.php",
	"/wp-admin/options.php", "/wp-admin/options-general.php",
	"/wp-admin/edit.php", "/wp-admin/post-new.php",
	"/wp-admin/media-new.php", "/wp-admin/page-new.php",
	"/wp-admin/plugin-install.php", "/wp-admin/theme-install.php",
	"/wp-admin/user-new.php", "/wp-admin/revision.php",
	"/wp-admin/customize.php", "/wp-admin/widgets.php",
	"/wp-admin/nav-menus.php", "/wp-admin/theme-editor.php",
	"/wp-admin/plugin-editor.php", "/wp-admin/includes/",
	"/wp-admin/includes/template.php", "/wp-admin/includes/upgrade.php",
	"/wp-includes/ms-functions.php", "/wp-includes/ms-blogs.php",
	"/wp-includes/load.php", "/wp-includes/class-wp-error.php",
	"/wp-content/debug.log", "/wp-content/advanced-cache.php",
	"/wp-content/wp-cache-config.php", "/wp-content/db.php",
	"/wp-content/mu-plugins/", "/wp-content/object-cache.php",
	"/wp-admin/wp-config.php", "/wp-config.php.bak",
	"/wp-config.php.old", "/wp-config.php.save",
	"/wp-config.php.swp", "/wp-config.php~",
	"/wp-config.php.dist", "/wp-config.php.example",
	"/wp-config-sample.php", "/wp-config.php.inc",
	"/wp-content/uploads/", "/wp-content/uploads/sites/",
	"/wp-content/upgrade/", "/wp-content/backups-dup-pro/",
	"/wp-content/updraft/", "/wp-content/ai1wm-backups/",
	"/wp-content/backup/", "/wp-content/backupwordpress/",
	"/wp-content/uploads/2023/", "/wp-content/uploads/2024/",
	"/wp-content/uploads/2025/", "/wp-content/uploads/2026/",
	"/wp-includes/js/tinymce/", "/wp-includes/js/jquery/",
	"/wp-includes/css/", "/wp-includes/images/",
	"/wp-admin/css/", "/wp-admin/images/", "/wp-admin/js/",
}

var PHPWebshells = []string{
	"c99.php", "r57.php", "b374k.php", "wso.php",
	"wso2.8.5.php", "shell.php", "cmd.php", "command.php",
	"webshell.php", "backdoor.php", "hack.php", "evil.php",
	"v.php", "n2r.php", "phpspy.php", "dbghelp.php",
	" Images.php", "1x.php", "sys-anal.php", "php-downloader.php",
	"mole.php", "lion.php", "angel.php", "b374k-2.2.php",
	"gamma.php", "alpha.php", "d.php", "c.php",
	"b.php", "a.php", "index.php", "default.php",
	"test.php", "info.php", "phpinfo.php", "config.php",
	"admin.php", "login.php", "uploader.php", "upload.php",
	"filemanager.php", "file.php", "editor.php",
	"mini-shell.php", "mini.php", "simple.php",
	"analyze.php", "analyze2.php", "analyze3.php",
	"asos.php", "hacker.php", "access.php", "anthracycline.php",
	"antichat.php", "b0xz.php", "babylon.php", "behinder.php",
	"behinder3.php", "behinder4.php", "blue.php",
	"byinv.php", "chaos.php", "chopper.php",
	"cknife.php", "clip.php", "cold.php", "control.php",
	"cyber.php", "dark.php", "data.php", "ddos.php",
	"ddos2.php", "decode.php", "deface.php", "defacer.php",
	"disk.php", "dir.php", "dirtree.php", "dirweb.php",
	"download.php", "dr.php", "dump.php", "eval.php",
	"exchange.php", "exploit.php", "expl0it.php",
	"fat.php", "filemanager.php", "find.php",
	"firefox.php", "fix.php", "flash.php", "ftp.php",
	"get.php", "grab.php", "gun.php", "h4ck.php",
	"head.php", "hidden.php", "huge.php", "hybrid.php",
	"i.php", "imhacks.php", "info.php", "inject.php",
	"injection.php", "intel.php", "j.php", "jack.php",
	"jays-webshell.php", "joker.php", "k.php",
	"kadot.php", "kameleon.php", "khost.php",
	"lamashell.php", "loader.php", "login.php",
	"luna.php", "ly00n.php", "madspot.php",
	"m0rnik.php", "marker.php", "max.php", "mem.php",
	"mini.php", "minicmd.php", "minishell.php",
	"monster.php", "morning.php", "multiple.php",
	"mysql.php", "myshell.php", "n.php", "nano.php",
	"nc.php", "netcat.php", "ninja.php",
	"orange.php", "pages.php", "panel.php",
	"pass.php", "passwd.php", "password.php",
	"pc.php", "p0c.php", "php-meter.php",
	"php-reverse-shell.php", "php-shell.php",
	"php.php", "phpbackdoor.php", "phpspy.php",
	"ping.php", "pl.php", "port.php",
	"powerful.php", "private.php", "proxy.php",
	"ps.php", "q.php", "query.php",
	"r.php", "r57.php", "red.php", "reverse.php",
	"rshell.php", "s.php", "safe.php", "scan.php",
	"secure.php", "shell.php", "shell2.php", "shell3.php",
	"shell4.php", "shell5.php", "shellz.php",
	"simple-backdoor.php", "simple.php", "simplecmd.php",
	"singles.php", "small.php", "sniper.php",
	"socks.php", "soho.php", "solorm.php",
	"speed.php", "sql.php", "sql2.php",
	"ssh.php", "start.php", "stop.php",
	"sym.php", "sys.php", "system.php",
	"t.php", "teams.php", "thelast.php",
	"tmp.php", "tools.php", "tunnel.php",
	"up.php", "upload.php", "uploader.php",
	"url.php", "v0rtex.php", "v1.php", "v2.php",
	"v3.php", "v4.php", "v5.php",
	"w.php", "web.php", "webshell.php",
	"windows.php", "wso.php", "x.php",
	"xx.php", "y.php", "z.php",
	"zehir.php", "zen.php", "zero.php",
	"zuo.php", "zz.php",
}

var GitPaths = []string{
	"/.git/", "/.git/HEAD", "/.git/config",
	"/.git/description", "/.git/index",
	"/.git/logs/", "/.git/logs/HEAD",
	"/.git/logs/refs/", "/.git/logs/refs/heads/",
	"/.git/logs/refs/heads/main", "/.git/logs/refs/heads/master",
	"/.git/logs/refs/heads/develop", "/.git/logs/refs/heads/dev",
	"/.git/objects/", "/.git/objects/pack/",
	"/.git/objects/info/", "/.git/objects/info/packs",
	"/.git/refs/", "/.git/refs/heads/",
	"/.git/refs/tags/", "/.git/refs/remotes/",
	"/.git/refs/remotes/origin/",
	"/.git/branches/", "/.git/branches/config",
	"/.git/branches/description",
	"/.git/hook/", "/.git/hook/pre-commit",
	"/.git/hook/post-commit", "/.git/hook/pre-push",
	"/.git/hook/commit-msg", "/.git/hook/update",
	"/.git/info/", "/.git/info/exclude",
	"/.git/packed-refs", "/.git/shallow",
	"/.git/COMMIT_EDITMSG", "/.git/FETCH_HEAD",
	"/.git/MERGE_HEAD", "/.git/ORIG_HEAD",
	"/.git/rebase-merge/", "/.git/rebase-apply/",
	"/.git/svn", "/.gitmodules",
	"/.gitattributes", "/.gitignore",
	"/.gitreview", "/.gitkeep",
	"/.github/", "/.github/workflows/",
	"/.github/ISSUE_TEMPLATE/",
	"/.github/CODEOWNERS", "/.github/dependabot.yml",
	"/.github/FUNDING.yml", "/.github/pull_request_template.md",
	"/.gitlab-ci.yml", "/.gitlab/",
	"/.git/hooks/", "/.git/hooks/post-receive",
	"/.git/hooks/pre-receive", "/.git/hooks/update",
}

var EnvFiles = []string{
	"/.env", "/.env.local", "/.env.dev", "/.env.development",
	"/.env.staging", "/.env.stage", "/.env.test",
	"/.env.production", "/.env.prod", "/.env.live",
	"/.env.example", "/.env.sample", "/.env.template",
	"/.env.default", "/.env.backup", "/.env.bak",
	"/.env.old", "/.env.save", "/.env.swp",
	"/.env.dist", "/.env.dev.local", "/.env.test.local",
	"/.env.prod.local", "/.env.local.php",
	"/.env.development.local", "/.env.production.local",
	"/.env.staging.local", "/.env.test.bak",
	"/.env.development.bak", "/.env.production.bak",
	"/.env.staging.bak", "/.env.test.backup",
	"/.env.development.backup", "/.env.production.backup",
	"/.env.staging.backup", "/.env.local.backup",
	"/.env.local.old", "/.env.local.bak",
	"/.env.local.swp", "/.env.local.save",
	"/.env.local.dist", "/.env.local.example",
	"/.env.local.sample", "/.env.local.template",
	"/.env.local.default",
	"/app.env", "/app.env.local", "/app.env.development",
	"/app.env.production", "/app.env.staging",
	"/app/.env", "/app/.env.local",
	"/app/.env.development", "/app/.env.production",
	"/src/.env", "/src/.env.local",
	"/src/.env.development", "/src/.env.production",
	"/config/.env", "/config/.env.local",
	"/config/.env.development", "/config/.env.production",
	"/backend/.env", "/backend/.env.local",
	"/backend/.env.development", "/backend/.env.production",
	"/api/.env", "/api/.env.local",
	"/api/.env.development", "/api/.env.production",
	"/.env.backup.1", "/.env.backup.2", "/.env.backup.3",
	"/.env.2023", "/.env.2024", "/.env.2025", "/.env.2026",
	"/.env.old.1", "/.env.old.2", "/.env.old.3",
	"/.env.bak.1", "/.env.bak.2", "/.env.bak.3",
	"/.env.save.1", "/.env.save.2", "/.env.save.3",
	"/.env.swp.1", "/.env.swp.2", "/.env.swp.3",
	"/.env~", "/.env.local~", "/.env.development~",
	"/.env.production~", "/.env.staging~",
	"/.env.gitignore", "/.env.gitkeep",
	"/docker/.env", "/docker/.env.local",
	"/docker/.env.development", "/docker/.env.production",
	"/docker/.env.staging", "/docker/.env.test",
	"/.env.d", "/.env.d.local", "/.env.d.development",
	"/.env.d.production", "/.env.d.staging",
	"/env.txt", "/env.bak.txt", "/env.old.txt",
	"/env.json", "/env.yaml", "/env.yml", "/env.xml",
	"/.env.json", "/.env.yaml", "/.env.yml", "/.env.xml",
}

var BackupFiles = []string{
	"/backup", "/backups", "/backup.sql", "/backups.sql",
	"/backup.tar.gz", "/backup.zip", "/backup.7z",
	"/db-backup", "/database-backup", "/sql-backup",
	"/dump.sql", "/dump.sql.gz", "/dump.sql.bak",
	"/database.sql", "/database.sql.gz", "/database.sql.bak",
	"/data.sql", "/data.sql.gz", "/data.sql.bak",
	"/schema.sql", "/seed.sql", "/migration.sql",
	"/backup.tar", "/backup.tgz", "/backup.tar.bz2",
	"/backup.gz", "/backup.xz", "/backup.zst",
	"/www.tar.gz", "/www.zip", "/www-backup",
	"/public.tar.gz", "/public.zip", "/public-backup",
	"/html.tar.gz", "/html.zip", "/html-backup",
	"/site.tar.gz", "/site.zip", "/site-backup",
	"/web.tar.gz", "/web.zip", "/web-backup",
	"/app.tar.gz", "/app.zip", "/app-backup",
	"/src.tar.gz", "/src.zip", "/src-backup",
	"/source.tar.gz", "/source.zip", "/source-backup",
	"/code.tar.gz", "/code.zip", "/code-backup",
	"/release.tar.gz", "/release.zip",
	"/deploy.tar.gz", "/deploy.zip",
	"/production.tar.gz", "/production.zip",
	"/staging.tar.gz", "/staging.zip",
	"/development.tar.gz", "/development.zip",
	"/.git-backup", "/.git.zip", "/.git.tar.gz",
	"/git-backup", "/git.zip", "/git.tar.gz",
	"/backup-2023", "/backup-2024", "/backup-2025", "/backup-2026",
	"/backup_2023", "/backup_2024", "/backup_2025", "/backup_2026",
	"/backup.1", "/backup.2", "/backup.3",
	"/backup.old", "/backup.bak", "/backup.orig",
	"/backup.new", "/backup.current", "/backup.latest",
	"/backup.prev", "/backup.previous",
	"/.backup", "/.backups", "/.backup.sql",
	"/old_backup", "/old_backups", "/new_backup",
	"/temp_backup", "/tmp_backup", "/temp.sql",
	"/tmp.sql", "/temp.sql.gz", "/tmp.sql.gz",
	"/mysql-backup", "/mysql-dump", "/mysqldump",
	"/pg-backup", "/pg-dump", "/pgdump",
	"/postgres-backup", "/postgres-dump",
	"/.db-backup", "/.db-dump", "/.database-backup",
	"/db.sql", "/db.sql.gz", "/db.sql.bak",
	"/sql.sql", "/sql.sql.gz", "/sql.sql.bak",
	"/export.sql", "/import.sql", "/migrate.sql",
	"/bak", "/bak/", "/bak.sql",
	"/bak.sql.gz", "/bak.tar.gz", "/bak.zip",
	"/.bak", "/.bak.sql", "/.bak.tar.gz",
	"/archive", "/archive.sql", "/archive.tar.gz",
	"/old", "/old.sql", "/old.tar.gz",
	"/backup_files", "/backup_configs", "/backup_db",
	"/backup_www", "/backup_html", "/backup_public",
	"/backup_app", "/backup_src", "/backup_code",
	"/backup_site", "/backup_web", "/backup_data",
	"/backup_prod", "/backup_staging", "/backup_dev",
	"/backup_live", "/backup_prod.sql", "/backup_staging.sql",
	"/backup_dev.sql", "/backup_live.sql",
	"/.sqlbackup", "/.sqlbackup.sql",
	"/sqlbackup", "/sqlbackup.sql",
}

var HiddenFiles = []string{
	"/.htaccess", "/.htpasswd", "/.htgroups",
	"/.ssh/", "/.ssh/authorized_keys", "/.ssh/id_rsa",
	"/.ssh/id_rsa.pub", "/.ssh/id_dsa", "/.ssh/id_dsa.pub",
	"/.ssh/id_ecdsa", "/.ssh/id_ecdsa.pub",
	"/.ssh/id_ed25519", "/.ssh/id_ed25519.pub",
	"/.ssh/config", "/.ssh/known_hosts", "/.ssh/authorized_keys2",
	"/.gitignore", "/.gitattributes", "/.gitmodules", "/.gitkeep",
	"/.env", "/.env.local", "/.env.production", "/.env.staging",
	"/.dockerignore", "/.docker/", "/.docker/config.json",
	"/.npmrc", "/.yarnrc", "/.pypirc",
	"/.gem/credentials", "/.cargo/credentials", "/.cargo/config",
	"/.aws/credentials", "/.aws/config", "/.aws/session-token",
	"/.azure/accessTokens.json", "/.azure/azureProfile.json",
	"/.gcloud/", "/.gcloud/credentials.db", "/.gcloud/properties",
	"/.kube/config", "/.kube/cache/",
	"/.bashrc", "/.bash_profile", "/.bash_login", "/.bash_logout",
	"/.bash_history", "/.zshrc", "/.zprofile", "/.zlogin",
	"/.zsh_history", "/.profile", "/.login", "/.logout",
	"/.vimrc", "/.emacs", "/.nanorc", "/.tmux.conf",
	"/.netrc", "/.pgpass", "/.my.cnf", "/.mylogin.cnf",
	"/.wget-hsts", "/.curl-hsts",
	"/.DS_Store", "/.DS_Store?", "/._.DS_Store",
	"/._.Trashes", "/.__MACOSX", "/.Spotlight-V100",
	"/.Trashes", "/.VolumeIcon.icns",
	"/Thumbs.db", "/ehthumbs.db", "/ehthumbs_vista.db",
	"/Desktop.ini", "/$RECYCLE.BIN/",
	"/.Trash-", "/.Trash-1000", "/.local/", "/.local/share/",
	"/.cache/", "/.config/", "/.config/prowl/",
	"/.local/share/prowl/", "/.config/opencode/",
	"/.editorconfig", "/.prettierrc", "/.eslintrc",
	"/.babelrc", "/.stylelintrc", "/.jshintrc",
	"/.pylintrc", "/.flake8", "/.mypy.ini",
	"/.phpunit.xml", "/.phpcs.xml",
	"/.docker-compose.override.yml",
	"/.docker-compose.override.yaml",
	"/.env.d", "/.env.d.local", "/.env.d.development",
	"/.env.d.production", "/.env.d.staging",
	"/.terraform/", "/.terraform.lock.hcl",
	"/.vagrant/", "/.vagrant.d/",
	"/.ansible/", "/.ansible-lint",
	"/.chef/", "/.chef/knife.rb",
	"/.puppet/", "/.puppetlabs/",
	"/.tox/", "/.pytest_cache/", "/.mypy_cache/",
	"/.coverage", "/.coveragerc",
	"/.nyc_output/", "/.istanbul.yml",
	"/.parcel-cache/", "/.next/", "/.nuxt/",
	"/.build/", "/.dist/", "/.output/",
	"/.venv/", "/.virtualenvs/", "/.envs/",
	"/.idea/", "/.vscode/", "/.vscode-server/",
	"/.projectile", "/.tags", "/.tags1",
	"/.TAGS", "/.GTAGS", "/.GRTAGS", "/.GSYMS",
	"/.cproject", "/.settings/",
	"/.firebaserc", "/.firebase/",
	"/.vercel/", "/.netlify/", "/.heroku/",
	"/.elasticbeanstalk/", "/.ebextensions/",
	"/.circleci/", "/.github/",
	"/.gitlab-ci.yml", "/.travis.yml", "/.appveyor.yml",
	"/.drone.yml", "/.codeship-services.yml",
	"/.secrets.baseline", "/.snyk",
}

var AdminPaths = []string{
	"/admin", "/admin/", "/admin/login", "/admin/dashboard",
	"/admin/index", "/admin/default", "/admin/main",
	"/administrator", "/administrator/", "/administrator/login",
	"/admin.php", "/admin.html", "/admin.cgi",
	"/wp-admin", "/wp-admin/", "/wp-admin/install.php",
	"/wp-admin/setup-config.php", "/wp-admin/upgrade.php",
	"/wp-admin/admin-ajax.php",
	"/cpanel", "/cpanel/", "/cpanel/login",
	"/whm", "/whm/", "/whm/login",
	"/plesk", "/plesk/", "/plesk/login",
	"/webmin", "/webmin/", "/webmin/login",
	"/phpmyadmin", "/phpmyadmin/", "/pma/",
	"/myadmin", "/mysql/", "/mysqladmin",
	"/adminer", "/adminer.php",
	"/console", "/console/", "/shell", "/shell/",
	"/jolokia", "/jolokia/",
	"/manager", "/manager/html", "/manager/text",
	"/manager/status", "/manager/jmxproxy",
	"/manager/start", "/manager/stop",
	"/host-manager", "/host-manager/html",
	"/host-manager/text",
	"/jenkins", "/jenkins/", "/jenkins/login",
	"/jenkins/script", "/jenkins/manage",
	"/gitlab", "/gitlab/", "/gitlab/users/sign_in",
	"/gitea", "/gitea/", "/gitea/user/login",
	"/gogs", "/gogs/", "/gogs/user/login",
	"/phabricator", "/phabricator/",
	"/sonar", "/sonar/", "/sonarqube/",
	"/nexus", "/nexus/", "/nexus3/",
	"/artifactory", "/artifactory/", "/artifactory/webapp/",
	"/grafana", "/grafana/", "/grafana/login",
	"/kibana", "/kibana/", "/kibana/login",
	"/prometheus", "/prometheus/",
	"/zabbix", "/zabbix/", "/zabbix/",
	"/nagios", "/nagios/", "/nagios/cgi-bin/",
	"/cacti", "/cacti/",
	"/munin", "/munin/",
	"/elasticsearch", "/_cat/indices", "/_cat/shards",
	"/_cluster/health", "/_nodes", "/_stats",
	"/kafka-manager", "/kafka-manager/",
	"/burp", "/burp/",
	"/metasploit", "/msfconsole",
	"/openvas", "/openvas/",
	"/owasp-zap", "/zap/",
	"/admin/config", "/admin/settings",
	"/admin/users", "/admin/groups",
	"/admin/logs", "/admin/audit",
	"/admin/backup", "/admin/import",
	"/admin/export", "/admin/maintenance",
	"/admin/cache", "/admin/clear",
	"/admin/restart", "/admin/reload",
	"/admin/health", "/admin/status",
	"/admin/info", "/admin/version",
	"/admin/debug", "/admin/test",
	"/admin/tools", "/admin/system",
	"/admin/security", "/admin/permissions",
	"/admin/roles", "/admin/api",
	"/admin/webhooks", "/admin/notifications",
	"/admin/email", "/admin/smtp",
	"/admin/database", "/admin/db",
	"/admin/file-manager", "/admin/media",
	"/admin/pages", "/admin/posts",
	"/admin/comments", "/admin/plugins",
	"/admin/themes", "/admin/menus",
	"/admin/widgets", "/admin/options",
	"/admin/general", "/admin/reading",
	"/admin/writing", "/admin/discussion",
	"/admin/privacy", "/admin/permalinks",
}

var UserEnumPaths = []string{
	"/wp-json/wp/v2/users", "/wp-json/wp/v2/users/1",
	"/wp-json/wp/v2/users/2", "/wp-json/wp/v2/users/3",
	"/?author=1", "/?author=2", "/?author=3",
	"/author/1", "/author/2", "/author/3",
	"/users", "/users/", "/users/list",
	"/api/users", "/api/users/", "/api/users/list",
	"/api/v1/users", "/api/v1/users/",
	"/api/user", "/api/user/",
	"/graphql?query={users{id,name,email}}",
	"/graphql?query={user(id:1){name,email}}",
	"/wp-login.php?action=register",
	"/wp-admin/user-new.php",
	"/xmlrpc.php?username=admin&password=test",
	"/feed/", "/comments/feed/",
	"/wp-json/wp/v2/posts?author=1",
	"/wp-json/wp/v2/pages?author=1",
	"/wp-json/wp/v2/comments?author=1",
	"/?author_name=admin",
	"/author/admin",
	"/author/root",
	"/author/test",
	"/users/registration", "/signup",
	"/register", "/register/",
	"/account", "/account/register",
	"/membership", "/membership/register",
	"/login", "/login/register",
	"/auth/register", "/auth/signup",
	"/api/auth/register", "/api/auth/signup",
	"/api/register", "/api/signup",
	"/graphql?query={accounts{id,username}}",
	"/graphql?query={account(id:1){username}}",
	"/debug/vars", "/debug/pprof",
	"/actuator/env", "/actuator/configprops",
	"/jolokia/list", "/metrics",
	"/server-info", "/server-status",
	"/phpinfo.php", "/info.php",
	"/?debug=true", "/?test=true",
	"/.env", "/config.json",
	"/config.yml", "/config.xml",
	"/database.yml", "/application.properties",
}

var wordlistData = map[WordlistName][]string{
	NameCommonPasswords:   CommonPasswordsList,
	NameCommonUsernames:   CommonUsernames,
	NameDirectoryWordlist: DirectoryWordlist,
	NameSubdomainWordlist: SubdomainWordlist,
	NameParameterWordlist: ParameterWordlist,
	NameBackupExtensions:  BackupExtensions,
	NameSensitiveFiles:    SensitiveFiles,
	NameDefaultCreds:      DefaultCreds,
	NameAPIEndpoints:      APIEndpoints,
	NameGraphQLWords:      GraphQLWords,
	NameCloudEndpoints:    CloudEndpoints,
	NameWordPressPaths:    WordPressPaths,
	NamePHPWebshells:      PHPWebshells,
	NameGitPaths:          GitPaths,
	NameEnvFiles:          EnvFiles,
	NameBackupFiles:       BackupFiles,
	NameHiddenFiles:       HiddenFiles,
	NameAdminPaths:        AdminPaths,
	NameUserEnumPaths:     UserEnumPaths,
}

func GetWordlist(name string) []string {
	if wl, ok := wordlistData[WordlistName(name)]; ok {
		return wl
	}
	return nil
}

func GetWordlistByName(name string) []string {
	return GetWordlist(name)
}

func ListWordlists() []string {
	var names []string
	for name := range wordlistData {
		names = append(names, string(name))
	}
	return names
}

func SaveWordlist(name, path string) error {
	wl, ok := wordlistData[WordlistName(name)]
	if !ok {
		return fmt.Errorf("unknown wordlist: %s", name)
	}

	if err := os.MkdirAll(filepath.Dir(path), 0755); err != nil {
		return fmt.Errorf("failed to create directory: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("failed to create file: %w", err)
	}
	defer f.Close()

	for _, line := range wl {
		fmt.Fprintln(f, line)
	}

	return nil
}

func SaveAllWordlists(dir string) (map[string]string, error) {
	paths := make(map[string]string)
	for name := range wordlistData {
		path := filepath.Join(dir, string(name)+".txt")
		if err := SaveWordlist(string(name), path); err != nil {
			return paths, fmt.Errorf("failed to save %s: %w", name, err)
		}
		paths[string(name)] = path
	}
	return paths, nil
}

func WordlistSize(name string) int {
	wl, ok := wordlistData[WordlistName(name)]
	if !ok {
		return 0
	}
	return len(wl)
}

func SearchWordlist(name, query string) []string {
	wl, ok := wordlistData[WordlistName(name)]
	if !ok {
		return nil
	}

	query = strings.ToLower(query)
	var results []string
	for _, entry := range wl {
		if strings.Contains(strings.ToLower(entry), query) {
			results = append(results, entry)
		}
	}
	return results
}
